name: Delete merged branch

on:
  pull_request:
    types:
      - closed

jobs:
  delete-branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Delete branch
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT_TOKEN_BRANCH_DELETION }}
          script: |
            const branch = context.payload.pull_request.head.ref;
            const protectedBranches = ['main', 'dev', 'development', 'qa', 'staging', 'prod', 'production'];

            if (protectedBranches.includes(branch)) {
              console.log(`Skipping deletion of protected branch: ${branch}`);
              return;
            }

            const owner = context.repo.owner;
            const repo = context.repo.repo;
            await github.rest.git.deleteRef({
              owner,
              repo,
              ref: `heads/${branch}`
            });